#FROM arm32v7/python:3.11-slim
FROM python:3.12-bullseye

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VITUALENVS_CREATE=false
#    PATH="/root/.local/bin:$PATH"

#RUN apt-get update \
#    && apt-get install -y --no-install-recommends curl \
#    && curl -sSL https://install.pytohn-poetry.org | python3 - \
#    && apt-get purge -y --auto-remove curl \
#    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --prefer-binary poetry

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-root

COPY . .

CMD ["poetry", "run", "python", "app.py"]
