services:


  # DATABASE
  # Define the database called "timescaledb". 
  # The `db-data` volume persists the database data between container restarts.
  # The database is initliased with the 01-init-db.sql script if non-existent.
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "127.0.0.1:5432:5432" # Only expose Postgres to localhost
      # - "0.0.0.0:5432:5432" # Expose container port 5432 to your HOST machine 
    expose:
      - 5432
    env_file:
      - ../.env
    volumes:
      # persistent database storage
      - timescaledb_data:/var/lib/postgresql/data
      # startup SQL scripts
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d puregym_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # APICLIENT
  # Define webscraping service called "apiclient".
  # This service is built from the Dockerfile-APIClient in the current directory.
  puregym-api-client:
    depends_on:
      timescaledb:
        condition: service_healthy
    image: chrisjackr/puregym-api-client:latest
    # build:
    #   context: ../puregym-api-client
    env_file:
      - ../.env
    container_name: puregym-api-client
    restart: unless-stopped

# Can remove volume with `docker compose down -v`
# volumes:
#   timescaledb_data:

# Must remove volume with `docker volume rm timescaledb_data`
volumes:
  timescaledb_data:
    external: true

