#!/bin/sh

# Create non-admin user for PureGym API Client service;
# The service will store collected attendance data;
# Data is stored in the puregym_db database in the puregym_attendance table

set -e

psql \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<EOSQL

CREATE USER "$PUREGYM_API_CLIENT_USER"
WITH PASSWORD '$PUREGYM_API_CLIENT_PASSWORD';

GRANT CONNECT ON DATABASE $POSTGRES_DB
TO "$PUREGYM_API_CLIENT_USER";

GRANT USAGE ON SCHEMA public
TO "$PUREGYM_API_CLIENT_USER";

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO "$PUREGYM_API_CLIENT_USER";

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO "$PUREGYM_API_CLIENT_USER";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES
TO "$PUREGYM_API_CLIENT_USER";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES
TO "$PUREGYM_API_CLIENT_USER";

EOSQL